#!/bin/bash

INPUT_LOCATION=$1
INPUT_DATA=$(cat $INPUT_LOCATION)

readarray -t INPUT_ARR <<< "$INPUT_DATA"

NUMBER_OF_VALID_PASSWORDS_PROBLEM_1=0

for INPUT in "${INPUT_ARR[@]}"
do
  IFS=' |\-|\:' read -ra INPUT_VALUES <<< "$INPUT"
  MINIMUM_CHARACTER_MATCH=${INPUT_VALUES[0]}
  MAXIMUM_CHARACTER_MATCH=${INPUT_VALUES[1]}
  SEARCH_CHARACTER=${INPUT_VALUES[2]}
  SEARCH_STRING=${INPUT_VALUES[3]}

  INPUT_WITH_ONLY_SEARCH_CHARACTERS="${SEARCH_STRING//[^${SEARCH_CHARACTER}]}"
  NUMBER_TIMES_SEARCH_CHARACTER_IN_INPUT="${#INPUT_WITH_ONLY_SEARCH_CHARACTERS}"
  if (( $MINIMUM_CHARACTER_MATCH <= $NUMBER_TIMES_SEARCH_CHARACTER_IN_INPUT && $NUMBER_TIMES_SEARCH_CHARACTER_IN_INPUT <= $MAXIMUM_CHARACTER_MATCH )); then
    NUMBER_OF_VALID_PASSWORDS_PROBLEM_1=$((NUMBER_OF_VALID_PASSWORDS_PROBLEM_1+1))
  fi

done

echo NUMBER OF PASSWORDS FOR PROBLEM 1: $NUMBER_OF_VALID_PASSWORDS_PROBLEM_1

NUMBER_OF_VALID_PASSWORDS_PROBLEM_2=0

for INPUT in "${INPUT_ARR[@]}"
do
  IFS=' |\-|\:' read -ra INPUT_VALUES <<< "$INPUT"
  FIRST_CHARACTER_LOCATION=$((${INPUT_VALUES[0]}-1))
  SECOND_CHARACTER_LOCATION=$((${INPUT_VALUES[1]}-1))
  SEARCH_CHARACTER=${INPUT_VALUES[2]}
  SEARCH_STRING=${INPUT_VALUES[3]}

  FIRST_CHARACTER_FOUND=${SEARCH_STRING:FIRST_CHARACTER_LOCATION:1}
  SECOND_CHARACTER_FOUND=${SEARCH_STRING:SECOND_CHARACTER_LOCATION:1}

  FIRST_CHARACTER_MATCH=$(expr "$FIRST_CHARACTER_FOUND" == "$SEARCH_CHARACTER")
  SECOND_CHARACTER_MATCH=$(expr "$SECOND_CHARACTER_FOUND" == "$SEARCH_CHARACTER")

  if [[ ($FIRST_CHARACTER_MATCH -eq 1 || $SECOND_CHARACTER_MATCH -eq 1) && FIRST_CHARACTER_MATCH -ne $SECOND_CHARACTER_MATCH ]]; then
    NUMBER_OF_VALID_PASSWORDS_PROBLEM_2=$((NUMBER_OF_VALID_PASSWORDS_PROBLEM_2+1))
  fi
done

echo NUMBER OF PASSWORDS FOR PROBLEM 2: $NUMBER_OF_VALID_PASSWORDS_PROBLEM_2